### ISSUE TITLE
1.20.1 Crash Reports

### ISSUE THREAD

**Issue by StrangeJoe2613** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#730] opened 2023-08-03 09:24 UTC
[crash-2023-08-03_17.21.13-fml.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/12249136/crash-2023-08-03_17.21.13-fml.txt)

**Comment by StrangeJoe2613** [comment] 2023-08-03 09:24
`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-08-03 17:21:13
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.1.58-universal.jar%23240!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.1.58-universal.jar%23240!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:163) ~[server-1.20.1-20230612.114412-srg.jar%23235!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.58.jar%23153!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.58.jar%23153!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.58.jar%23153!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%2384!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:95) [mohist-1.20.1-268-server.jar:1.20.1-268] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.1.58.jar%23153!/:1.0] {}
-- MOD mtr --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
		at mtr.mappings.ForgeUtilities.<clinit>(ForgeUtilities.java:40) ~[%5BMTR%5D我的世界铁路MTR-forge-1.20-3.2.2-hotfix-1.jar%23198!/:?] {re:classloading}
		at mtr.MTRForge.<clinit>(MTRForge.java:34) ~[%5BMTR%5D我的世界铁路MTR-forge-1.20-3.2.2-hotfix-1.jar%23198!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.58.jar%23237!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.58.jar%23236!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /E:/Minecraft Server/mods/[MTR]我的世界铁路MTR-forge-1.20-3.2.2-hotfix-1.jar
	Failure message: Minecraft Transit Railway (mtr) has failed to load correctly
		java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
	Mod Version: 1.20-3.2.2-hotfix-1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.1.58.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at mtr.mappings.ForgeUtilities.<clinit>(ForgeUtilities.java:40) ~[%5BMTR%5D我的世界铁路MTR-forge-1.20-3.2.2-hotfix-1.jar%23198!/:?] {re:classloading}
	at mtr.MTRForge.<clinit>(MTRForge.java:34) ~[%5BMTR%5D我的世界铁路MTR-forge-1.20-3.2.2-hotfix-1.jar%23198!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.1.58.jar%23237!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.58.jar%23236!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Mohist Version: 1.20.1-268
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows Server 2022 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 507386424 bytes (483 MiB) / 826277888 bytes (788 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
	Identifier: Intel64 Family 6 Model 85 Stepping 7
	Microarchitecture: Cascade Lake
	Frequency (GHz): 3.31
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Microsoft Hyper-V 视频
	Graphics card #0 vendor: Microsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=10.0.20348.1
	Graphics card #1 name: Microsoft Remote Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.0.20348.1
	Memory slot #0 capacity (MB): 3968.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4224.00
	Memory slot #1 clockSpeed (GHz): 0.00
	Memory slot #1 type: Other
	Virtual memory max (MB): 10710.52
	Virtual memory used (MB): 2999.20
	Swap memory total (MB): 2518.97
	Swap memory used (MB): 412.91
	JVM Flags: 2 total; -Xmx8192M -Xms512M
	CraftBukkit Information: CraftServer is not running yet
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.58.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.58.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.58.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.58.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.58.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar I18nUpdateMod TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		[功能]潘马斯农场2pamhc2trees-1.20-1.0.2.jar              |Pam's HarvestCraft 2 - Trees  |pamhc2trees                   |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		[JEI物品管理器核心]JEI物品管理器 - Forge1.20.1.jar            |Just Enough Items             |jei                           |15.2.0.23           |COMMON_SET|Manifest: NOSIGNATURE
		[功能]自定义史蒂夫模型Yes Steve Model - Forge1.20.1.jar     |Yes Steve Model               |yes_steve_model               |1.1.5-hotfix-2      |COMMON_SET|Manifest: NOSIGNATURE
		[功能]简单血条Neat-1.20-35-FORGE.jar                    |Neat                          |neat                          |1.20-35-FORGE       |COMMON_SET|Manifest: NOSIGNATURE
		[功能]Xaero的世界地图Xaero's WorldMap - Forge1.20.1.jar  |Xaero's World Map             |xaeroworldmap                 |1.31.0              |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.8.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.8        |COMMON_SET|Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.3.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.1.58-universal.jar                |Forge                         |forge                         |47.1.58             |COMMON_SET|Manifest: NOSIGNATURE
		[暮色森林核心]暮色森林The Twilight Forest - Forge1.20.1.jar |The Twilight Forest           |twilightforest                |4.3.1740            |COMMON_SET|Manifest: NOSIGNATURE
		[生长工艺核心]生长工艺GrowthCraft - Forge1.20.1.jar         |Growthcraft                   |growthcraft                   |9.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]更多箱子Iron Chests - Forge1.20.1.jar             |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事核心]农夫乐事Farmer's Delight - Forge1.20.1.jar    |Farmer's Delight              |farmersdelight                |1.20.1-1.2.2a       |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]末地乐事ends delight - Forge1.20.1.jar        |End's Delight                 |ends_delight                  |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]玉米乐事前置MMLib妖怪之山通用库 - Forge1.20.1.jar      |Mysterious Mountain Lib       |mysterious_mountain_lib       |1.2.7-1.20          |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]末影乐事endersdelight - Forge1.20.1.jar       |Ender's Delight               |endersdelight                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]高亮显示Jade-1.20.1-forge-11.4.1.jar              |Jade                          |jade                          |11.4.1              |COMMON_SET|Manifest: NOSIGNATURE
		[功能]潘马斯农场2pamhc2crops-1.20-1.0.2.jar              |Pam's HarvestCraft 2 - Crops  |pamhc2crops                   |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]潘马斯农场2pamhc2foodextended-1.20-1.0.0.jar       |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.20-0.6.9-4.jar                   |Flywheel                      |flywheel                      |0.6.9-4             |COMMON_SET|Manifest: NOSIGNATURE
		[机械动力核心]机械动力Create - Forge1.20.1.jar              |Create                        |create                        |0.5.1.d             |COMMON_SET|Manifest: NOSIGNATURE
		[功能]帕秋莉手册Patchouli-1.20.1-81-FORGE.jar            |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		[功能]Xaero的小地图Xaero's MiniMap - Forge1.20.1.jar    |Xaero's Minimap               |xaerominimap                  |23.6.0              |COMMON_SET|Manifest: NOSIGNATURE
		[功能]潘马斯农场2pamhc2foodcore-1.20-1.0.0.jar           |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]通用拼音搜索jecharacters-1.20.1-4.4.1.jar           |Just Enough Characters        |jecharacters                  |1.20.1-4.4.1        |COMMON_SET|Manifest: NOSIGNATURE
		[功能]口渴ThirstRemade-1.0.4.jar                      |Thirst Remade                 |thirst                        |1.20.1-1.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]暮色风味乐事Twilight Flavors & Delight - Forge1.|Twilight's Flavor & Delight   |twilightdelight               |2.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		[装饰]MrCrayfish 的家具.jar                            |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		[功能]苹果皮appleskin - Forge1.20.1.jar                |AppleSkin                     |appleskin                     |2.5.0+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		[前置]architectury-9.1.12-forge.jar                 |Architectury                  |architectury                  |9.1.12              |COMMON_SET|Manifest: NOSIGNATURE
		[MTR]我的世界铁路MTR-forge-1.20-3.2.2-hotfix-1.jar      |Minecraft Transit Railway     |mtr                           |1.20-3.2.2-hotfix-1 |ERROR     |Manifest: NOSIGNATURE
		[农夫乐事拓展]海洋乐事oceansdelight - Forge1.20.1.jar       |Ocean's Delight               |oceansdelight                 |1.0.2-1.20          |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]玉米乐事corn delight - Forge1.20.1.jar        |Corn Delight                  |corn_delight                  |1.0.3-1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		[功能]高亮显示拓展JadeAddons-1.20.1-forge-5.1.0.jar       |Jade Addons                   |jadeaddons                    |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]料理乐事前置l2library - Forge1.20.1.jar         |L2 Library                    |l2library                     |2.4.11              |COMMON_SET|Manifest: NOSIGNATURE
		l2tabs-0.1.4.jar                                  |L2 Tabs                       |l2tabs                        |0.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]莱特兰-扩充l2complements-2.4.14.jar                |L2 Complements                |l2complements                 |2.4.14              |COMMON_SET|Manifest: NOSIGNATURE
		[功能]莱特兰-弓艺l2archery-2.4.7.jar                     |L2 Archery                    |l2archery                     |2.4.7               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]莱特兰-武器l2weaponry-2.4.8.jar                    |L2 Weaponry                   |l2weaponry                    |2.4.8               |COMMON_SET|Manifest: NOSIGNATURE
		[功能]莱特兰-背包l2backpack-2.4.8.jar                    |L2 Backpack                   |l2backpack                    |2.4.8               |COMMON_SET|Manifest: NOSIGNATURE
		l2screentracker-0.1.2.jar                         |L2 Screen Tracker             |l2screentracker               |0.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		l2damagetracker-0.1.4.jar                         |L2 Damage Tracker             |l2damagetracker               |0.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		l2itemselector-0.1.3.jar                          |L2 Item Selector              |l2itemselector                |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		[农夫乐事拓展]料理乐事Cuisine Delight - Forge1.20.1.jar     |Cuisine Delight               |cuisinedelight                |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		[机械动力拓展]机械动力附魔工业Create Enchantment Industry - Forg|Create Enchantment Industry   |create_enchantment_industry   |1.2.6               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: d3e482fb-2571-4743-83ac-b6d15e398a58
	FML: 0.0
	Forge: net.minecraftforge:47.1.58`

**Comment by kettle-7** [comment] 2023-08-03 20:39
Are you running in a vm ?

**Comment by StrangeJoe2613** [comment] 2023-08-04 00:08
> Are you running in a vm ?

nope,im running in the VPS server.

**Comment by kettle-7** [comment] 2023-08-07 00:00
Please try reproduce this on actual hardware as it seems like that might be the cause.

**Comment by Kinokoda** [comment] 2023-08-12 09:42
Same stuff here on bare metal. I have been trying to host this mod on a private server for me and some friends but the server crashes when it starts up, I will provide you with a crash report in a sec.

**Comment by kettle-7** [comment] 2023-08-12 20:36
Apparently MTR doesn't support servers on 1.20 until the Minecraft Mappings project is done (or done enough for MTR to use it)

**Comment by Kenny-Hui** [comment] 2024-02-12 12:47
Duplicate of #701

**Closed by Kenny-Hui** 2024-02-12 12:47 UTC
Labels: bug, duplicate
