### ISSUE TITLE
automatic plaform gates stay open when there is no train after upausing game

### ISSUE THREAD

**Issue by oplog999** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#833] opened 2024-04-22 10:22 UTC
**Expected Behaviour**
i expected them to close

**Actual Behaviour**
they stayed open

**Reproduction Steps**
Steps to reproduce the behaviour:

1.pause game while train is at station
2wait a few seconds then unpause the game

**Crash Report**
this dosent crash the game

**Screenshots**
![2024-04-22_20 13 52](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/167760130/656ba77d-a7a1-414d-aa16-092cf567f08b)

**Environment**

- Minecraft Version:1.20.1
- Installed Mods:

**Additional Information**
Anything else you want to add?

**Comment by Ultimate-USA-YT** [comment] 2024-04-22 18:30
MTR on 1.20.1 isn't known for it Running Well.

**Comment by jonafanho** [comment] 2024-06-24 17:31
Duplicate of #699

**Closed by jonafanho** 2024-06-24 17:31 UTC
Labels: bug, fixed in next release
