### ISSUE TITLE
(Forge) MTR-forge-1.20-3.2.2-hotfix-1.jar installation crashed on server

### ISSUE THREAD

**Issue by garrett20090** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#729] opened 2023-08-01 15:40 UTC
There is a crash problem when installed in 1.20.1, and there is no problem in 1.19.4

**Comment by kettle-7** [comment] 2023-08-02 21:53
The mod doesn't support 1.20 on servers yet, and the client support is only experimental. Please just use 1.19 for the time being.

**Comment by Kenny-Hui** [comment] 2024-02-12 14:32
Duplicate of #701

**Closed by Kenny-Hui** 2024-02-12 14:32 UTC
Labels: bug, duplicate
