### ISSUE TITLE
the sign get weird when x or y is really big

### ISSUE THREAD

**Issue by SkeletoNCY** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#593] opened 2022-12-29 16:43 UTC
the sign just flashes abnormally when the coordinate is vert big (>=100k)
![3](https://user-images.githubusercontent.com/53283266/209983301-b9f27d23-8475-47dc-87fb-752cf8c4a4f3.png)
![2](https://user-images.githubusercontent.com/53283266/209983317-fd1367f4-a64a-40dc-8b83-f055ed440af3.png)
they just flash everywhere or even disappeared

**Comment by XHG78999** [comment] 2023-01-04 02:43
> the sign just flashes abnormally when the coordinate is vert big (>=100k) ![3](https://user-images.githubusercontent.com/53283266/209983301-b9f27d23-8475-47dc-87fb-752cf8c4a4f3.png) ![2](https://user-images.githubusercontent.com/53283266/209983317-fd1367f4-a64a-40dc-8b83-f055ed440af3.png) they just flash everywhere or even disappeared

I remembered that @Zbx1425 have introduced about this bug. MTR is using 32-bit float on many rendering calucations. Like farlands, it may caused by the float loss.
To solve the problem, we should replace all of 32-bit float to 64-bit float. It is a huge work, so we should wait before 3.2.0.

**Comment by jonafanho** [comment] 2024-06-24 17:14
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!

**Closed by jonafanho** 2024-06-24 17:14 UTC
Labels: bug, fixed in next release
