### ISSUE TITLE
When running with create, the train of create will make a critical attack sound

### ISSUE THREAD

**Issue by UQRARA** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#443] opened 2022-07-21 16:33 UTC
**describe**
When create0.5.0 and mtr3.0.1 are installed in the game, critical attack sound will be triggered when the physical train in create runs at high speed

**Reproduction Steps**
1. Build the train in create0.5.0
2. Start the train and reach one third of the speed bar
3. A continuous and cyclic critical attack sound will be sent

**Environment**
- Minecraft Version: 1.18.2
- Installed Mods:
- MTR-forge-1.18.2-3.0.1
- create-mc1.18.2_v0.5.0c
- flywheel-forge-1.18-0.6.4
- architectury-4.5.76-forge
- Forge 40.1.31
- OptiFine HD_U_H7

**Comment by Ultimate-USA-YT** [comment] 2022-07-21 20:56
Try asking in the Create Github

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment] 2022-09-05 07:20
I think this is caused by `mtr:seat` which constantly chases player and it's invisible entity, but they didn't add this as expection, which caused this. they tries to knockback `mtr:seat` entity, but it constantly comes back, which causes this. reopen this issue please?

**Comment by jonafanho** [comment] 2022-09-05 20:04
Thanks for the additional info.

**Comment by jonafanho** [comment] 2024-06-24 16:04
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!

**Closed by jonafanho** 2024-06-24 16:04 UTC
Labels: mod compatibility
