### ISSUE TITLE
The rail tracks are not loading!

### ISSUE THREAD

**Issue by Pranav2222** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#510] opened 2022-09-28 04:30 UTC
Hello,
I have experienced this issue where the tracks won't even load, which includes all types of rails with the basic given MTR mod. I have joban client installed, LU installed, and XaerosWorldMap with XaerosMiniMap. I don't have optifine because my game is crashing with it on. I play on the 1.18.2 version with forge 1.18.2 / 40.1.69 installed.

When I place a new track with nodes just for testing they work, but when I leave and join the game again they disappear and only the nodes are visible!

Any fixing for this?

**I desperately need this fixed as I've been working on this project with MTR for over 3 months. I need quick help.**

**Comment by jonafanho** [comment] 2022-09-28 16:31
Please post all logs, crash reports, and screenshots of your mods folder.

**Comment by kettle-7** [comment] 2022-09-29 03:37
When abouts did this start happening? Was it after updating the mod?

**Comment by Pranav2222** [comment] 2022-10-02 16:19
ok here are the pics
![Minecraft transit railway mods](https://user-images.githubusercontent.com/114554371/193464424-c2f9b438-72c8-48d3-8a93-97390e3e701b.png)
![Invisible tracks](https://user-images.githubusercontent.com/114554371/193464638-2a373008-9d10-404f-98ee-acc6ab311ed0.png)
![Untitled](https://user-images.githubusercontent.com/114554371/193464753-f10ec441-fc49-446f-99f2-4da460d535df.png)
![No stations!](https://user-images.githubusercontent.com/114554371/193464774-4c912037-6999-4baf-9bce-aa926fb9a734.png)

**Comment by Pranav2222** [comment] 2022-10-02 16:19
oh btw i am in superflat

**Comment by Pranav2222** [comment] 2022-10-02 16:20
> When abouts did this start happening? Was it after updating the mod?

Um kinda, but I faced this problem before but restarting the game fixed it. But now it didn't.

**Comment by Pranav2222** [comment] 2022-10-02 16:25
> Please post all logs, crash reports, and screenshots of your mods folder.

Ummm no crashes without optifine, the mod Is stable without optifine for me, but with it crashes appear.

**Comment by Pranav2222** [comment] 2022-10-02 16:25
![Blank signals](https://user-images.githubusercontent.com/114554371/193465045-d5e1fda7-75fe-4069-93f8-3560927c4aed.png)
another bug...

**Comment by kettle-7** [comment] 2022-10-02 21:55
I think the best thing to do is try on 3.1.2 with a new world and see if the problem is solved. If it is then try load the old world in the same version.

**Comment by Pranav2222** [comment] 2022-10-03 06:43
> I think the best thing to do is try on 3.1.2 with a new world and see if the problem is solved. If it is then try load the old world in the same version.

Hmm ill definitely try that.

**Comment by Pranav2222** [comment] 2022-10-03 06:46
> I think the best thing to do is try on 3.1.2 with a new world and see if the problem is solved. If it is then try load the old world in the same version.

Did you mean 3.1.1? because I am already in 3.1.2

**Comment by Pranav2222** [comment] 2022-10-06 08:29
Uhhh yep I tried creating a world in 3.1.2 and 3.1.1 and same issue.

**Comment by mull1111** [comment] 2022-12-25 04:35
Or you may want to update your mtr to 3.1.12. (I don't know, but it is worth a try. Because the version you are using is too old.)

**Comment by Blackcheckgamer** [comment] 2023-09-11 12:49
I've got the same issue.
Playing on a fabric 1.19.2 Server with Version 3.2.0 of MTR all Configurations, Stations etc. randomly disappeared.
Upgrading to 3.2.2-hotfix-1 fixed the problem temporarily. 
After a week all information was lost again, but now i get a stack trace:
[logSnapshot.txt](https://github.com/jonafanho/Minecraft-Transit-Railway/files/12576100/logSnapshot.txt)
My used Mods: 
<img width="455" alt="image" src="https://github.com/jonafanho/Minecraft-Transit-Railway/assets/75884629/9bb38baa-bcc9-407a-be7e-6b77b33e1ce1">

**Comment by jonafanho** [comment] 2024-06-24 16:48
This should be fixed in 4.0.0. Please reopen this bug if you still encounter this issue with 4.0.0, thanks!

**Closed by jonafanho** 2024-06-24 16:48 UTC
Labels: bug
