### ISSUE TITLE
Ad Astra Lander not working

### ISSUE THREAD

**Issue by Drakune** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#713] opened 2023-07-04 10:41 UTC
**Expected Behaviour**
Fly to planet and stay in lander vehicle

**Actual Behaviour**
When flying to any planet using ad astra rockets, you get thrown out of the lander and die, devs said the problem is on your side

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Fly to other planet with Ad Astra and Transit railway mod installed

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version: 1.20.1
- Installed Mods: https://pastebin.com/kNxJ4x0N

**Additional Information**
Anything else you want to add?

**Comment by Ultimate-USA-YT** [comment] 2023-07-05 03:12
How is this Related to MTR?

**Comment by Drakune** [comment] 2023-07-05 10:21
As soon as yoo install MTR the bug appears. The deve of ad astra said they alteady sent you a way hot wo fix this but the issue got deleted

**Comment by Drakune** [comment] 2023-07-05 10:22
https://github.com/terrarium-earth/Ad-Astra/issues/319

**Comment by Drakune** [comment] 2023-07-15 01:15
Any updates/plans to look into this issue?

**Comment by Kenny-Hui** [comment] 2024-02-10 19:11
Duplicate of #427 
See https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues/427#issuecomment-1937095312

**Closed by Kenny-Hui** 2024-02-10 19:11 UTC
Labels: duplicate, mod compatibility
