### ISSUE TITLE
[Suggestion] More features for Lift

### ISSUE THREAD

**Issue by CKFA** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#632] opened 2023-02-26 11:02 UTC
**1. Doors for 4 Sides.**

Currently, lift only opens for two sides instead of 4 sides. 
Thus, I would like to suggest for adding another two side, it would be increased flexibility for builders.

**2. Custom Sound for Lift.**

As those stations in MTR. There are broadcastings which plays in the lift, such as: "Going up", "This lift has arrived at Concourse.", "Platform for XXX lines."

**3. Different style of Lift.**

Eg. full metal door, lift with no glass surrounding, different display panel, display panel at the top of the door inside the lift.

**4. Levels Display Guide.**

A sticker showing all levels what use, the one always be put nearby the lift door.

**Comment by saleem0915** [comment] 2023-03-15 21:13
Are you basically saying like what #598 is saying?

**Comment by CKFA** [comment] 2023-03-26 16:51
> Are you basically saying like what #598 is saying?

Not really. The one I suggest is allow the Lift Door can be setuped in different orientations (4 sides), not the door design. Currently only able to open doors same times in opposite directions but not supports to set a door in both sides (left and right).

**Comment by jonafanho** [comment] 2024-06-24 16:18
Duplicate of #598

**Closed by jonafanho** 2024-06-24 16:18 UTC
Labels: duplicate, enhancement
