### ISSUE TITLE
Re-support of the model customization of PSD/APG and customization settings of showing route-map

### ISSUE THREAD

**Issue by XHG78999** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#601] opened 2023-01-07 08:33 UTC
**Is your feature request related to a problem? Please describe.**
After a version (i have forgotten it), the running way of PSD/APG has changed a lot. The doors used the TileEntityRender to show. That means old format PSD/APG addition and custom PSD/APG models all be cannot use.
In addition, some of custom PSD/APG model have no position to place route-map. Not only this but also in some server, we'll use some mods like OPF2 or SlideShow to show our own route-map style.

**Describe the solution you'd like**
Support for old PSD/APG style. 
Use iron hoe (or others) and right click on PSD Showing Block/APG to open/close the showing of route-map.

**Additional Information**
It should support for the different models of left and right door.

**Comment by jonafanho** [comment] 2024-06-24 16:20
Duplicate of #196

**Closed by jonafanho** 2024-06-24 16:20 UTC
Labels: duplicate, enhancement
