### ISSUE TITLE
the platform screen doors are glitched when i place them in 1.20 curseforge with fabric api and architectury

### ISSUE THREAD

**Issue by thingy108** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#705] opened 2023-06-24 15:11 UTC
**Expected Behaviour**
I expect the platform doors to open when a train opens its doors.

**Actual Behaviour**
When i place them down with a train at the platform, the doors are half place as shown and they dont open. 

**Reproduction**
^^^^^^^^^^^
it is there!

1.

**Crash Report**
dont have a crash report

**Screenshots**

**Environment**
environment?
- Minecraft Version: 1.20.1
- Installed Mods: Architectury,  Better FPS,     Collective,       Fabric API,     FPS-Display,      Minecraft Transit Railway,      Sounds Physics Remastered,             Tree Chopper,             World Edit,  all of which are on CurseForge.

![jonafan2](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/137528681/02660ea9-6eb7-4edd-873b-42dd2121946d)

**Additional Information**
Johnathan, pls fix this for my peoplemover and big railway
![jonafan1](https://github.com/jonafanho/Minecraft-Transit-Railway/assets/137528681/35545b16-af67-4fbc-a39c-0e3f2a2e6960)

**Comment by thingy108** [comment] 2023-06-24 15:14
They also dont break!

**Comment by thingy108** [comment] 2023-06-24 15:16
I think i found an annoying fix but please still fix it

**Comment by thingy108** [comment] 2023-06-30 15:20
thanks

**Comment by VoodooSP** [comment] 2023-07-16 07:03
but how can i do for syncing the data?**F3+A does not work**

**Comment by CStafford-14** [comment] 2023-09-20 17:43
> this is singleplayer

Even in a single player world, Minecraft starts its own server with only 1 max player - you - so it's still possible for the client (what you see) and server (what happens behind the scenes) to become desynced.

I guess this explains why leaving and rejoining fixes everything, it just needs to be re-synced! I have many mods installed on my client (and on the server since I run a modded server), would any of them break this or is it just an alpha build acting up?

**Comment by kettle-7** [comment] 2023-09-20 20:18
I'm not exactly sure but the only way really to find out is by testing on 1.19.x.

The 1.20 build is full of bugs, some known, others not, but currently the main priority is on mtr version 4.0.0, which, as it is a near full rewrite, will likely not have many of these bugs anyway.

**Comment by jonafanho** [comment] 2024-06-24 16:57
Duplicate of #727

**Closed by jonafanho** 2024-06-24 16:57 UTC
Labels: bug, fixed in next release
