### ISSUE TITLE
Train Route KI is bugged

### ISSUE THREAD

**Issue by BoborMBI2** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#785] opened 2023-12-11 12:13 UTC
**Expected Behaviour**
The Train should ride the shortest route

**Actual Behaviour**
The train rides around the complete world

**Crash Report**
Attach a crash report to the issue.

**Screenshots**

**Environment**

- Minecraft Version: 1.19.2
- Installed Mods: MTR, LU Underground, Nemos Transit
![Bild_2023-12-11_131328635](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/136601467/f3b5cb27-c45b-4c39-85a5-ac23d8a6b65d)

Green is the actual way
Red the bugged one

**Comment by Reddwar** [comment] 2024-01-06 14:26
I am also experiencing this issue in my world.  I have an East-West track and a North-South track that join each other.  The East-west train will turn onto the northbound track, go all the way to the end then turn back to rejoin the westbound track.

**Comment by Kenny-Hui** [comment] 2024-03-07 11:51
Duplicate of #710

**Closed by Kenny-Hui** 2024-03-07 11:51 UTC
