### ISSUE TITLE
Cant place rails

### ISSUE THREAD

**Issue by YsS15651w6** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#754] opened 2023-09-27 17:27 UTC
**Expected Behaviour**
Rails to be placed without game crashing

**Actual Behaviour**
Game world saves and crashes

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Use rail nodes and connectors to connect rails
2. 2. Game crashes

**Crash Report**
[https://mclo.gs/lrVmtrl]

**Screenshots**
No screenshots are possible

**Environment**

- Minecraft Version: 1.19.4
- Installed Mods: MTR and Architectury

**Additional Information**
Is it possibly my version or PC?

**Comment by kettle-7** [comment] 2023-09-30 02:01
This is very strange, your forge and architectury versions are fine, it doesn't seem like an issue with your laptop, I am quite confused.

**Comment by Kenny-Hui** [comment] 2024-02-13 05:44
Duplicate of #744

**Closed by Kenny-Hui** 2024-02-13 05:44 UTC
