### ISSUE TITLE
The One Probe Compatibility issue?

### ISSUE THREAD

**Issue by blockbreaker1361** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#400] opened 2022-06-19 13:09 UTC
When you look straight down whether your cursor is looking directly at a block/item or not, all it shows is the title of your mod. I tried it in every dimension in the pack and the result is always the same. 
![2022-06-19_09 01 30](https://user-images.githubusercontent.com/5491411/174482633-353047c5-b493-45e9-b991-2dae69954daf.png)

**Comment by kettle-7** [comment] 2022-06-20 04:12
Yes, this is because there's an invisible pig under you that attracts to
you and draws all the trains. There's not really much we can do unless
hwyla adds a feature to allow to hide entities from the tooltip.

**Comment by heipiao233** [comment] 2022-06-22 15:00
and WALIA(Jade/WTHIT)?

**Comment by ProsperCraft** [comment] 2022-06-23 16:09
We are having the same problem with Jade.  The players are really annoyed.
![image](https://user-images.githubusercontent.com/4427684/175345196-3b18a6e6-b917-42bc-b14a-a806ce23ba81.png)

**Comment by markthomas007** [comment] 2023-01-27 21:18
I made a fork of the Jade Additions mod adding a fix for the invisible entity. You just add this mod along side of the Jade mod to fix the invisible entity. Its only for 1.19.2 since I'm still learning how to mod. Ill add some other versions later.
If you have the regular version of the Jade Addons mod you will need to remove it before putting mine in.

Hope this helps! 😃 
https://github.com/markthomas007/JadeAddonsFabricWithMTR/

**Comment by jonafanho** [comment] 2024-06-24 17:04
Duplicate of #341

**Closed by jonafanho** 2024-06-24 17:04 UTC
Labels: duplicate, mod compatibility, fixed in next release
