### ISSUE TITLE
接触网和js

### ISSUE THREAD

**Issue by JiaqiYi** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#848] opened 2024-05-22 09:57 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: I'm always frustrated when...

**Describe the solution you'd like**
为确保可靠性,希望接触网可以添加到mtr 本体。
希望nte 的列车js 功能和装饰物件被合并。

**Additional Information**

**Comment by jonafanho** [comment] 2024-06-24 17:24
Duplicate of #548 and #844

**Closed by jonafanho** 2024-06-24 17:24 UTC
Labels: duplicate, enhancement
