### ISSUE TITLE
cant open inventory as when i do game crashes

### ISSUE THREAD

**Issue by Nitrodude472** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#846] opened 2024-05-20 07:04 UTC
**Expected Behaviour**
to find it in my inventory

**Actual Behaviour**
i load up the world fine but when i load the infventory it crashes my game 

**Reproduction Steps**
Steps to reproduce the behaviour:

1. 

**Crash Report**
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" is null

**Environment**

- Minecraft Version:  1.20.1
- Installed Mods:

**Comment by Kenny-Hui** [comment] 2024-05-20 10:28
Duplicate of #794

**Closed by Kenny-Hui** 2024-05-20 10:28 UTC
Labels: bug, duplicate
