### ISSUE TITLE
Ad Astra Lander bug

### ISSUE THREAD

**Issue by DragonMotion** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#748] opened 2023-09-05 06:57 UTC
**Expected Behaviour**
Fly to planet and stay in lander vehicle

**Actual Behaviour**
When flying to any planet using ad astra rockets, you get thrown out of the lander.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Install Ad Astra.
2. place a tier 1 rocket on the pad
3. shift click and add a bucket of rocket fuel
4. get in the rocket and press space
5. select earth, then moon
6. spawn without a Lander

**Environment**

- Minecraft Version: 1.19.2
- Installed Mods: Ad Astra, Minecraft Transit Railway

**Comment by DragonMotion** [comment] 2023-09-05 07:11
There are no problems without the "Minecraft Transit Railway" mod. I also noticed that the mod can often cause dimensions problems. So on one of my servers, the mod causes a cyclic loading of the first dimension from Divine RPG. Please fix it.

**Comment by DragonMotion** [comment] 2023-09-07 21:25
I saw a message from other users. This is a fairly long-standing problem. The developers of the "Ad Astra" mod and users say that the problem is on the side of the "Minecraft Transit Railway" and that it can be solved, but it must be done by the author of the mod. Perhaps the mod affects the behavior of the player when loading a dimension, perhaps the developer can make a setting or config that will exclude some dimensions. Unfortunately, it seems that this problem is not a priority. I, like others, faced a problem and decided to raise the topic again. I hope the author of this wonderful mod will find the time and a solution, or make a setting that will allow you to exclude certain changes until a solution is found. Now the mod is destroying the game with extra dimensions.

**Comment by Atmois** [comment] 2023-09-23 23:42
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/427

**Comment by Kenny-Hui** [comment] 2024-02-10 19:02
Duplicate of #427

**Closed by Kenny-Hui** 2024-02-10 19:02 UTC
Labels: duplicate, mod compatibility
