### ISSUE TITLE
Make ticket currency configurable.

### ISSUE THREAD

**Issue by shantih19** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#711] opened 2023-07-02 00:29 UTC
Hi,
I really like the ticket system, but I'd love if there was a way to set a currency to use instead of emeralds (and maybe even set the exchange rates).
Is there already a way to do it that I may be missing?

**Comment by jonafanho** [comment] 2024-06-24 16:39
Duplicate of #359

**Closed by jonafanho** 2024-06-24 16:39 UTC
Labels: duplicate, enhancement

**Comment by ajh123** [comment] 2024-09-22 12:30
@jonafanho 

Definitely not a duplicate of #359, #359 is about changing the shape of fare zones, this suggestion is about changing the item used to pay.
