### ISSUE TITLE
Automatic Platform Assigning

### ISSUE THREAD

**Issue by FeedCat02** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#753] opened 2023-09-26 13:20 UTC
Be able to select multiple platforms at the same station for a train line and have the train pick between these platforms which one to use (pick an available one). So if you have a station with 4 platforms and you select platforms 1,2,3 the train will arrive in one of those, lets say platform 1.  Then another train arrives before the previous one leaves now it can pick between platforms 2,3 due to platform 1 already having a train.

**Comment by Ultimate-USA-YT** [comment] 2023-09-26 19:44
Suggested way to many times

**Comment by jonafanho** [comment] 2024-06-24 16:49
Duplicate of #537

**Closed by jonafanho** 2024-06-24 16:49 UTC
Labels: duplicate, enhancement
