### ISSUE TITLE
Creating a path

### ISSUE THREAD

**Issue by Gamestudiox-t3ryo** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#917] opened 2024-07-25 13:28 UTC
### Suggestion Type

Other

### Suggestion

It would be good if a path could be created sometime manualy for trains to travel on, because sometimes I find that the train goes somewhere I don't want it to go

**Comment by Kenny-Hui** [comment] 2024-08-03 15:44
Duplicate of #665

**Closed by Kenny-Hui** 2024-08-03 15:44 UTC
Labels: enhancement
