### ISSUE TITLE
360° Nodes | 全方向節點

### ISSUE THREAD

**Issue by ACS-resources** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#654] opened 2023-03-25 07:53 UTC
It's still really hard to build straight lines or slopes that are not parallel to the x and z axes
Add a new type of node which just make a straight line connecting each other when linked by a rail.
MTR支持的軌道傾斜角度還是太少，修建一部分斜着的軌道有些困難。可以加入一種新的節點，當連接它們時直接創建一條筆直的鐵軌。

Sincerely hope that the modder team can add this because it's pretty necessary.

**Comment by EpicPuppy613** [comment] 2023-03-28 19:10
The main issue here is a seamless transition between the usual system of nodes and this kind of node. You would essentially have to get some weird system that gets the angle of connections between this node and the next and use that as the base of the gradual slope.

**Comment by XHG78999** [comment] 2023-03-31 08:55
> The main issue here is a seamless transition between the usual system of nodes and this kind of node. You would essentially have to get some weird system that gets the angle of connections between this node and the next and use that as the base of the gradual slope.

in fact, control the calculation of bezier curve(like rtm done) can do this in a very easy-control way(but it also needs you to learn a lot about maths)

**Comment by SethPederito2023** [comment] 2023-03-31 19:06
Since it wias not 360 Node

**Comment by jonafanho** [comment] 2024-06-24 16:41
Duplicate of #332

**Closed by jonafanho** 2024-06-24 16:41 UTC
Labels: duplicate, enhancement
