### ISSUE TITLE
Game crashes when trying to craft mtr:pids_1_1

### ISSUE THREAD

**Issue by Cuetsu** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#909] opened 2024-07-13 15:30 UTC
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [ ] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

Hey, trying to craft this immediately crashes my game. The moment the outcome of the recipe is visible in the crafting table, my game freezes then crashes. I also tried to cheat in the items shown in the second screenshot from JEI (mtr:pids_1_1/mtr:pids_2/mtr:pids_3/mtr:pids_4/mtr:pids_single_arrival_1), all of them end up in a crash. Is there a way to fix this?

![image](https://github.com/user-attachments/assets/e98b18d6-a1c3-4dc2-b818-1de2ec9c0819)
![image](https://github.com/user-attachments/assets/aa096f05-194b-47a4-8fdf-393668c5f9f0)

### Reproduction Steps

- Trying to craft (mtr:pids_1_1/mtr:pids_2/mtr:pids_3/mtr:pids_4/mtr:pids_single_arrival_1).
- Having any (mtr:pids_1_1/mtr:pids_2/mtr:pids_3/mtr:pids_4/mtr:pids_single_arrival_1) in my inventory by using /give.

### In-game Log and Crash Report

[latest.log](https://github.com/user-attachments/files/16202701/latest.log)

[crash-2024-07-13_18.24.36-client.txt](https://github.com/user-attachments/files/16202702/crash-2024-07-13_18.24.36-client.txt)

### Mod Loader

Forge

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

MTR-forge-1.20.1-3.2.2-hotfix-2

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

[Minecolonies Dimensional Adventure ](https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure) 2.0.5-Hotfix

Additional mods:
- Enderman Overhaul
- Euphoria Patches
- Compatibility addon for Minecolonies
- Nether Remastered
- Immersive Melodies
- Distant Horizons

**Comment by Kenny-Hui** [comment] 2024-07-13 15:54
Duplicate of #794

**Closed by Kenny-Hui** 2024-07-13 15:54 UTC
Labels: bug
