### ISSUE TITLE
Game crash after hovering some items

### ISSUE THREAD

**Issue by Atilla5990** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#782] opened 2023-12-03 09:00 UTC
When i hover over some items in the mod it will crash the game

it's like that glass fence thingy (I don't remember what it is called) that will crash the game after hovering

**Comment by Kenny-Hui** [comment] 2024-02-19 13:09
Cannot reproduce this myself, but based on other report, it's likely caused by the same bug in #794 when using the MTR 3.2.2 1.20 alpha, which should be resolved by MTR 4.

@Atilla5990 Would be appreciated if you could supply more information, such as the crash report (If you still have it), Minecraft version, modloader and the mod you have installed for further confirmation.

**Comment by Kenny-Hui** [comment] 2024-06-20 12:25
Not enough information, this is very likely fixed in MTR 4

**Closed by Kenny-Hui** 2024-06-20 12:25 UTC
Labels: bug, not enough information
