### ISSUE TITLE
Support for 1.21

### ISSUE THREAD

**Issue by yeying-xingchen** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#951] opened 2024-09-08 14:19 UTC
### Suggestion Type

Other

### Suggestion

Adding support for 1.21.x, it's really important to me, please!

**Comment by Kenny-Hui** [comment] 2024-09-08 16:52
Please be patient as there's only a very limited of amount working on this mod.
Duplicate of #934

**Closed by Kenny-Hui** 2024-09-08 16:52 UTC
Labels: enhancement
