### ISSUE TITLE
GUIGraphics?

### ISSUE THREAD

**Issue by Engry1960** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#759] opened 2023-10-10 05:02 UTC
**Expected Behaviour**
Server to run.

**Actual Behaviour**
Crashing due to /GUIGraphics for invalid DIST.

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Upload mod to server hosting platform(APEX HOSTING MC)

**Crash Report**
10.10 04:57:22 [Server] INFO -- Head --
10.10 04:57:22 [Server] INFO Thread: main
10.10 04:57:22 [Server] INFO Stacktrace:
10.10 04:57:22 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.1.jar%2369!/:1.0] {}
10.10 04:57:22 [Server] INFO -- MOD mtr --
10.10 04:57:22 [Server] INFO Details:
10.10 04:57:22 [Server] INFO Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
10.10 04:57:22 [Server] INFO at mtr.mappings.ForgeUtilities.<clinit>(ForgeUtilities.java:40) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23306!/:?] {re:classloading}
10.10 04:57:22 [Server] INFO at mtr.MTRForge.<clinit>(MTRForge.java:34) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23306!/:?] {re:classloading}
10.10 04:57:22 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
10.10 04:57:22 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
10.10 04:57:22 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
10.10 04:57:22 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23355!/:?] {}
10.10 04:57:22 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23354!/:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
10.10 04:57:22 [Server] INFO Mod File: /mods/MTR-forge-1.20-3.2.2-hotfix-1.jar
10.10 04:57:22 [Server] INFO Failure message: Minecraft Transit Railway (mtr) has failed to load correctly
10.10 04:57:22 [Server] INFO java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
10.10 04:57:22 [Server] INFO Mod Version: 1.20-3.2.2-hotfix-1
10.10 04:57:22 [Server] INFO Mod Issue URL: NOT PROVIDED
10.10 04:57:22 [Server] INFO Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/GuiGraphics for invalid dist DEDICATED_SERVER
10.10 04:57:22 [Server] INFO Stacktrace:
10.10 04:57:22 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.1.jar%2369!/:1.0] {}
10.10 04:57:22 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
10.10 04:57:22 [Server] INFO at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
10.10 04:57:22 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
10.10 04:57:22 [Server] INFO at mtr.mappings.ForgeUtilities.<clinit>(ForgeUtilities.java:40) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23306!/:?] {re:classloading}
10.10 04:57:22 [Server] INFO at mtr.MTRForge.<clinit>(MTRForge.java:34) ~[MTR-forge-1.20-3.2.2-hotfix-1.jar%23306!/:?] {re:classloading}
10.10 04:57:22 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
10.10 04:57:22 [Server] INFO at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
10.10 04:57:22 [Server] INFO at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
10.10 04:57:22 [Server] INFO at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23355!/:?] {}
10.10 04:57:22 [Server] INFO at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23354!/:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
10.10 04:57:22 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Environment**

- Minecraft Version: 1.20.1
- Installed Mods:
[Ash API (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/ash-api)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Multi-Piston (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[FTB Ranks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ranks-forge)
[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Farming for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[FTB Quests (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Advanced Generators (by bdew)](https://www.curseforge.com/minecraft/mc-mods/advanced-generators)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Better Fusion Reactor for Mekanism PLUS (by igentuman)](https://www.curseforge.com/minecraft/mc-mods/better-fusion-reactor-for-mekanism)
[Rechiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Paintings ++ (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/paintings)
[WTHIT Harvestability (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-harvestability)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Apothic Attributes (AttributesLib) (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apothic-attributes)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
[Scalable Cat's Force (by Kotori316)](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force)
[XP From Harvest (Stoutscientist's Fork) (by Stoutscientist)](https://www.curseforge.com/minecraft/mc-mods/xp-from-harvest-forked)
[Light Overlay (Rift/Forge/Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/light-overlay)
[Sit (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/sit)
[BdLib (by bdew)](https://www.curseforge.com/minecraft/mc-mods/bdlib)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Emojiful (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/emojiful)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[FTB Essentials (Forge & Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[EpheroLib (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/epherolib)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[XL Packets (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Portable Mobs (by Dremoline)](https://www.curseforge.com/minecraft/mc-mods/portable-mobs)
[Bountiful (Forge) (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/bountiful)
[Chunk Animator (by Lumien231)](https://www.curseforge.com/minecraft/mc-mods/chunk-animator)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Forgiving Void (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/forgiving-void)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Kambrik (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Construction Wand (by ThetaDev)](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Mining Gadgets (by Direwolf20)](https://www.curseforge.com/minecraft/mc-mods/mining-gadgets)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Minecraft Transit Railway (Automated trains, planes, and more!) (by jonafanho)](https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway)
[Blood Magic (by WayofTime)](https://www.curseforge.com/minecraft/mc-mods/blood-magic)
[Starter Kit (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
[Pick Up Notifier [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Exline's Furniture Mod (by exlinegames)](https://www.curseforge.com/minecraft/mc-mods/exlines-furniture)
[Vending Machine (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/vending-machine)
[Nether Portal Spread (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Item Filters (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Refined Storage (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[Lost Features (by KaboomRoads)](https://www.curseforge.com/minecraft/mc-mods/lost-features)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Easy Villagers (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/easy-villagers)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Origins (Forge) (by EdwinMindcraft)](https://www.curseforge.com/minecraft/mc-mods/origins-forge)
[Fantasy's Furniture (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Mekanism-MoreSolarPanels (by Pocky)](https://www.curseforge.com/minecraft/mc-mods/mekanism-moresolarpanels)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Origins++ (by QuantumXenon)](https://www.curseforge.com/minecraft/mc-mods/origins-plus-plus)
[Yet Another World Protector (by z0rdak)](https://www.curseforge.com/minecraft/mc-mods/yawp)
[Shoppy (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/shoppy)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[ItemPhysic Full (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/itemphysic)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Iron Ender Chests (by lupiiin_)](https://www.curseforge.com/minecraft/mc-mods/iron-ender-chests)
[Ender Trigon (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/ender-trigon)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[Refined Storage Addons (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons)
[WTHIT Forge Edition (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-forge)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Money and Sign Shops (by caltinor)](https://www.curseforge.com/minecraft/mc-mods/dicemc-money-mod)

**Additional Information**
Attempting a World SMP server for my students in my class. There are upwards of 50 students playing at a time.

**Comment by kettle-7** [comment] 2023-10-10 18:53
MTR is not compatible with 1.20

**Comment by Kenny-Hui** [comment] 2024-02-12 12:46
Duplicate of #701

**Closed by Kenny-Hui** 2024-02-12 12:46 UTC
Labels: bug, duplicate
