### ISSUE TITLE
It's so creazy...

### ISSUE THREAD

**Issue by AGH11111** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#756] opened 2023-10-01 09:14 UTC
Game Version:1.20.1
Mod Loader:Fabric-0.14.21-1.20.1 and FabricAPI-0.86.1
Mod Version:fabric-1.20-3.2.2-hotfix
Video Mod:Sodium 0.5.2
Iris Ver:1.6.8
[Video.zip](https://github.com/jonafanho/Minecraft-Transit-Railway/files/12776777/Video.zip)

**Comment by Ultimate-USA-YT** [comment] 2023-10-02 18:55
1.20 MTR Runs like Tuna Salad on a V6 Gas Engine running on Diesel. Poorly. It is not Recommended Untill 4.0.0 Comes out

**Comment by kettle-7** [comment] 2023-10-03 01:39
to rephrase this in a way that makes sense please use 1.19.4 until mtr is next updated, which i would expect to be around the new year but can't be entirely sure

**Comment by Kenny-Hui** [comment] 2024-02-12 14:11
Duplicate of #755

**Closed by Kenny-Hui** 2024-02-12 14:11 UTC
Labels: bug, duplicate
